# Generated by Django 4.2 on 2023-04-08 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_data(apps, schema_editor):
    # qui puoi inserire il codice per creare i dati di default
    # ad esempio:
    User = apps.get_model('auth', 'User')
    user = User.objects.create(username='utente1', password='password')
    Project = apps.get_model('myapp', 'Project')
    project = Project.objects.create(name='Progetto 1', description='Descrizione del progetto 1', created_by=user)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RunPython(create_default_data),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='projects')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
