# Generated by Django 4.2 on 2023-04-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(),
        ),
    ]
